import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

// Register Service Worker for Offline Capabilities (Safe Mode)
if ('serviceWorker' in navigator) {
  // We attempt to register the SW if it exists (generated by build)
  // This prevents the "virtual:pwa-register" module crash in preview environments
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').then(registration => {
      console.log('SW registered: ', registration);
    }).catch(registrationError => {
      console.log('SW registration failed: ', registrationError);
    });
  });
}

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error("Could not find root element to mount to");
}

const root = ReactDOM.createRoot(rootElement);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);